services:
  postgres:
    image: postgres:16-alpine
    container_name: easymenu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: easymenu
      POSTGRES_PASSWORD: easymenu
      POSTGRES_DB: easymenu
    ports:
      - "5432:5432"
    volumes:
      - easymenu_postgres_data:/var/lib/postgresql/data

volumes:
  easymenu_postgres_data:
