ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "ingredients" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "variantsJson" JSONB;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "modifiersJson" JSONB;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "comboJson" JSONB;
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "availableFrom" TIMESTAMP(3);
ALTER TABLE "MenuItem" ADD COLUMN IF NOT EXISTS "availableTo" TIMESTAMP(3);
